-- Create table 1
CREATE DATABASE test;
USE test;

CREATE TABLE table1 (ID INT, Value VARCHAR(10));

INSERT INTO table1 (ID,Value)
SELECT 1, 'First'
UNION ALL
SELECT 2, 'Second'
UNION ALL
SELECT 3, 'Third'
UNION ALL
SELECT 4, 'Fourth'
UNION ALL
SELECT 5, 'Fifth';


-- Create table2 
CREATE TABLE table2 (ID INT, Value VARCHAR(10));
INSERT INTO table2(ID,Value)
SELECT 1, 'First'
UNION ALL
SELECT 2, 'Second'
UNION ALL
SELECT 3, 'Third'
UNION ALL
SELECT 6, 'Sixth'
UNION ALL
SELECT 7, 'Seventh'
UNION ALL
SELECT 8, 'Eighth';